const RETRIEVE_PLAYERS = 'RETRIEVE_PLAYERS';
const RETRIEVE_PLAYERS_SUCCESS = 'RETRIEVE_PLAYERS_SUCCESS';
const RETRIEVE_PLAYERS_FAILURE = 'RETRIEVE_PLAYERS_FAILURE';

export default { RETRIEVE_PLAYERS, 
  RETRIEVE_PLAYERS_SUCCESS, 
  RETRIEVE_PLAYERS_FAILURE
}