const RETRIEVE_PLAYERS = "RETRIEVE_PLAYERS";
const RETRIEVE_PLAYERS_SUCCESS = "RETRIEVE_PLAYERS_SUCCESS";
const RETRIEVE_PLAYERS_FAILURE = "RETRIEVE_PLAYERS_FAILURE";
const SET_SEARCHTERMS = "SET_SEARCHTERMS";

export default {
  RETRIEVE_PLAYERS,
  RETRIEVE_PLAYERS_SUCCESS,
  RETRIEVE_PLAYERS_FAILURE,
  SET_SEARCHTERMS
};
